webapp:
    build: .
    command: make startwebapp
    working_dir: /flatworld
    volumes:
        - .:/flatworld
    ports:
        - "8000:8000"
    links:
        - db:db
        - frontend:frontend
    env_file: .env
    expose:
        - "8000"

frontend:
    build: .
    command: make startfrontend
    working_dir: /flatworld
    volumes:
        - .:/flatworld
    ports:
        - "9000:9000"
    links:
        - db:db
    env_file: .env
    expose:
        - "9000"

db:
    image: mdillon/postgis:9.4
    volumes:
        - ./postgres_data:/var/lib/postgresql
    ports:
        - "9999:5432"
    volumes_from:
        - data

data:
    image: mdillon/postgis:9.4
    volumes:
        - /var/lib/postgresql
    command: "true"
