webapp:
    build: .
    command: make startwebapp
    env_file: .env
    expose:
        - "8000"
    links:
        - db
        - frontend
    ports:
        - "8000:8000"
    restart: always
    volumes:
        - .:/flatworld

frontend:
    build: .
    command: make startfrontend
    env_file: .env
    expose:
        - "9000"
    links:
        - db
        - dbserver
        - game
        - proxy
    ports:
        - "9000:9000"
    restart: always
    volumes:
        - .:/flatworld

game:
    build: .
    command: make startgameserver
    env_file: .env
    expose:
        - "5200"
    links:
        - dbserver
        - proxy
    ports:
        - "5200:5200"
    restart: always
    volumes:
        - .:/flatworld

dbserver:
    build: .
    command: make startdbserver
    env_file: .env
    ports:
        - "5000:5000"
    expose:
        - "5000"
    links:
        - db
    restart: always
    volumes:
        - .:/flatworld

proxy:
    build: .
    command: make startpubsubproxy
    env_file: .env
    ports:
        - "5100:5100"
        - "5101:5101"
    expose:
        - "5101"
    restart: always
    volumes:
        - .:/flatworld

staticwatch:
    build: .
    command: make staticwatch
    restart: always
    volumes:
        - .:/flatworld

tilestache:
    build: .
    command: make starttilestache
    env_file: .env
    expose:
        - "8080"
    links:
        - db
    ports:
        - "8080:8080"
    restart: always
    volumes:
        - .:/flatworld

db:
    image: mdillon/postgis:9.4
    ports:
        - "9999:5432"
    restart: always
    volumes_from:
        - data

data:
    command: "true"
    image: mdillon/postgis:9.4
    volumes:
        - /var/lib/postgresql
        - /etc/postgresql
        - /var/log/postgresql
    restart: always
